name: flutter_map_dragmarker
description: Dragmarker class for flutter_map
version: 7.0.0
repository: https://github.com/ibrierley/flutter_map_dragmarker

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map:
    git:
      url: https://github.com/RBT22/flutter_map.git
      ref: overlay-filter-quality

  latlong2: ^0.9.0

dev_dependencies:
  flutter_lints: ">=1.0.4"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

publish_to: 'none'